### ISSUE TITLE
两个问题和两个请教

### ISSUE THREAD

**Issue by komomon** [kscript/markdown-download#2]
1.微信文章未滑到底加载所有图片的时候，点击下载，未加载的图片不会被下载成功，看代码和创建的urls文件中可以看到未匹配到url，但是浏览器打开文章，不往下滑，图片不加载，但是view-source:，图片的链接是存在的，不太清楚为什么代码中匹配不到img标签，const files = queryAll('img', markdownBody).map(item ......

2.代码中的console.log并不会在控制台输出内容。

3.const markdownBody = query(selectors.body).cloneNode(true) markdownBody 是什么类型，不能使用.innerHTML输出吗
我想使用
 files.push({
    // name: realName + '/urls',
    name: 'Body' + '.html',
    content: markdownBody.toString()
  })
来查看问题1为什么匹配不到图片链接

4.如何调试js代码呢，我不是开发，对npm js不太了解，但是有些文章想要下载，对这个项目比较感兴趣。
大佬有考虑做成webapi接口的形式吗，我想要调用这个项目，感觉很不错。

**Comment by kscript** [comment]
1. 微信文章做了懒加载, 没有加载的图片, 真实的图片地址还在data-src属性上, 插件里没有去取 (加上了, 说实话本来没打算做)

2. 没有找到的 console.log输出的内容, 是在插件的背景页里

3. markdownBody 是 DOM元素, 文章内容所在的容器 (可以使用markdownBody.innerHTML, 不过插件里会在克隆出来的markdownBody元素上做改动)

4. 如果要调试的话, 参考README.md里使用方法, 改完npm run build一下
