### ISSUE TITLE
对知乎专栏文章的公式支持不好

### ISSUE THREAD

**Issue by Saltsmart** [kscript/markdown-download#3]
示例：https://zhuanlan.zhihu.com/p/506342644
下载后公式没有识别：

![image](https://user-images.githubusercontent.com/40828952/218392767-eed276ec-af43-4685-831e-5c10bad7f2cf.png)

**Comment by Saltsmart** [comment]
您好！这似乎是一系列知乎转markdown工具都有的问题，是否说明知乎已经更改了前端中公式的相关逻辑？

**Comment by kscript** [comment]
这个需要额外做处理, 我周末加一下.

**Comment by kscript** [comment]
调研了下, 各个网站显示公式用的是 `MathJax` 或 `KaTeX` 这两种解决方案
## MathJax
#### svg图片
- 简书
- 掘金
#### 页面标签
- 知乎
- 博客园
- 开源中国
## KaTeX
#### mathml + html
- 思否
- CSDN
